In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

C:\Users\HP\Anaconda3.0\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
dataset = pd.read_csv('Wine.csv')

In [3]:
X = dataset.drop('Customer_Segment', axis=1)
y = dataset['Customer_Segment']

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler_x = StandardScaler()

In [8]:
X_train = scaler_x.fit_transform(X_train)
X_test = scaler_x.transform(X_test)

C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\HP\Anaconda3.0\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [11]:
lda = LDA(n_components=2)

In [12]:
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
classifier = LogisticRegression()

In [15]:
classifier.fit(X_train, y_train)

C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 23  0]
 [ 0  0 15]]


In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        15

   micro avg       1.00      1.00      1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

