In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\HP\Anaconda3.0\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
dataset = pd.read_csv('Wine.csv')

In [3]:
dataset.columns

Index(['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline',
       'Customer_Segment'],
      dtype='object')

In [15]:
X = dataset.drop('Customer_Segment', axis=1)
y = dataset['Customer_Segment']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler_x = StandardScaler()

In [20]:
X_train = scaler_x.fit_transform(X_train)
X_test = scaler_x.transform(X_test)

C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\HP\Anaconda3.0\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [21]:
from sklearn.decomposition import PCA

In [22]:
pca = PCA(n_components=2)

In [23]:
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [24]:
explained_variance = pca.explained_variance_ratio_

In [25]:
print(explained_variance)

[0.37093753 0.19391146]


In [26]:
 from sklearn.linear_model import LogisticRegression

In [27]:
classifier = LogisticRegression()

In [28]:
classifier.fit(X_train, y_train)

C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HP\Anaconda3.0\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

In [31]:
print(confusion_matrix(y_test, y_pred))

[[13  1  0]
 [ 1 24  0]
 [ 0  0 15]]


In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.93      0.93      0.93        14
           2       0.96      0.96      0.96        25
           3       1.00      1.00      1.00        15

   micro avg       0.96      0.96      0.96        54
   macro avg       0.96      0.96      0.96        54
weighted avg       0.96      0.96      0.96        54

